language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx-2
  - jruby-19mode
script: "bundle exec rake test"

gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile

matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/4.0.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/4.1.gemfile
