name: CI
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.1
          - 2.2
          - 2.3
          - "jruby-9.3.2.0"
        gemfile:
          - "3.0"
          - "3.1"
          - "3.2"
          - "4.0"
          - "4.1"
          - "4.2"
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake test
