name: CI
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.1
          - 2.2
          - 2.3
          - "jruby-9.3.2.0"
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake test
